using Engine.Attributes;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static SourceGenCommon;




[Generator]
public sealed class DataValueGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (spc, compilation) =>
            {


                static ISymbol[] GetDataValueFields(ITypeSymbol type, Compilation compilation)
                {
                    var attributeSymbol = compilation.GetTypeByMetadataName(
                        typeof(DataValueAttribute).FullName);

                    var results = new List<ISymbol>();

                    for (var current = type; current != null; current = current.BaseType)
                    {
                        foreach (var member in current.GetMembers())
                        {
                            if (member is not (IFieldSymbol or IPropertySymbol))
                                continue;

                            if (member.GetAttributes().Any(a =>
                                SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeSymbol)))
                            {
                                results.Add(member);
                            }
                        }
                    }

                    return results.ToArray();
                }





                var allTypes = GetAllTypes(compilation.Assembly.GlobalNamespace).Where(x => GetDataValueFields(x, compilation).Any()).ToArray();



                var SB = new StringBuilder();




                SB.AppendLine("// <auto-generated />");
                SB.AppendLine("namespace Engine.Core;");
                SB.AppendLine("using System;");
                SB.AppendLine();

                SB.AppendLine("public static partial class Parsing");
                SB.AppendLine("{");



                SB.AppendLine($"\tpublic static void SetDataValues(object obj, Dictionary<byte, object> args)");
                SB.AppendLine("\t{");

                SB.AppendLine("\t\tvar objType = obj.GetType();");

                SB.AppendLine();




                for (int i = 0; i < allTypes.Length; i++)
                {

                    INamedTypeSymbol? type = allTypes[i];



                    var values = GetDataValueFields(type, compilation);


                    var typename = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);






                    SB.AppendLine();
                    SB.AppendLine();
                    SB.AppendLine($"//-------------------------------------- [ {typename} ] --------------------------------------");
                    SB.AppendLine();
                    SB.AppendLine();


                    SB.AppendLine($"\t\tif (objType == typeof({typename}))");
                    SB.AppendLine("\t\t{");
                    SB.AppendLine();
                    SB.AppendLine($"\t\t\tif (args != null)");
                    SB.AppendLine("\t\t\t{");



                    for (int i1 = 0; i1 < values.Length; i1++)
                    {
                        SB.AppendLine();


                        var param = values[i1];


                        var valGet = $"val_{type.Name}_{param.Name}_get";

                        var paramtypename = (param is IFieldSymbol f ? f.Type : ((IPropertySymbol)param).Type).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);


                        SB.AppendLine($"\t\t\t\tif (args.TryGetValue({i1}, out var {valGet}))");
                        SB.AppendLine($"\t\t\t\t\t(({typename})obj).{param.Name} = ({paramtypename}){valGet};");
                    }


                    spc.AddSource(
                        typename.Replace(":", "_").Replace(".", "_").Replace("+", "_") + ".g.cs", 
                        GenerateIntoType(type, 

                        $"/// <remarks>" +
                        $"<br/> --------------------------------------------- " +
                        $"<br/> [<see cref = \"{(typeof(DataValueAttribute).FullName)}\"/>] Users:" +
                        $"<br/> --------------------------------------------- \n" +
                        string.Join("\n", values.Select(param => $"/// <br/> - <see cref = \"{param.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{param.Name}\"/>")) +
                        "\n/// <br/> </remarks>", 
                        
                        string.Empty));




                    SB.AppendLine();


                    SB.AppendLine("\t\t\t}");

                    SB.AppendLine();
                    SB.AppendLine();
                    SB.AppendLine($"\t\t\treturn;");



                    SB.AppendLine();



                    SB.AppendLine("\t\t}");


                }


                SB.AppendLine();
                SB.AppendLine();
                SB.AppendLine("\t\tthrow new Exception();");


                SB.AppendLine();
                SB.AppendLine();


                SB.AppendLine("\t}");


                SB.AppendLine("}");

                spc.AddSource("DataValue.g.cs", SB.ToString());


            });
    }


}