using Microsoft.CodeAnalysis;
using System.Linq;
using System.Text;
using static SourceGenCommon;




[Generator]
public sealed class GameResourceGlueGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (spc, compilation) =>
            {



                var allTypes = GetAllTypes(compilation.Assembly.GlobalNamespace);



                var gameResourceSB = new StringBuilder();




                gameResourceSB.AppendLine("// <auto-generated />");
                gameResourceSB.AppendLine("namespace Engine.Core;");
                gameResourceSB.AppendLine("using System;");
                gameResourceSB.AppendLine();

                gameResourceSB.AppendLine("public partial class GameResource");
                gameResourceSB.AppendLine("{");




                var resourceBase =
                    compilation.GetTypeByMetadataName(
                        "Engine.Core.GameResource");


                var resourceTypes =
                    allTypes
                        .Where(t => DerivesFrom(t, resourceBase))
                        .ToArray();



                var ConstructGameResourceFromGeneric_SB = new StringBuilder();

                ConstructGameResourceFromGeneric_SB.AppendLine("\tpublic static partial async Task<GameResource> LoadGameResourceFromGenericAndStream<T>(Loading.AssetByteStream stream, string key) where T : GameResource");
                ConstructGameResourceFromGeneric_SB.AppendLine("\t{");
                ConstructGameResourceFromGeneric_SB.AppendLine(); 



                var ConstructGameResourceFromTypeID_SB = new StringBuilder();

                ConstructGameResourceFromTypeID_SB.AppendLine("\tpublic static partial async Task<GameResource> LoadGameResourceFromTypeIDAndStream(ushort TypeID, Loading.AssetByteStream stream, string key)");
                ConstructGameResourceFromTypeID_SB.AppendLine("\t{");
                ConstructGameResourceFromTypeID_SB.AppendLine();
                ConstructGameResourceFromTypeID_SB.AppendLine("\t\treturn TypeID switch");
                ConstructGameResourceFromTypeID_SB.AppendLine("\t\t{");



                var LoadGameResourceFromTypeID_SB = new StringBuilder();

                LoadGameResourceFromTypeID_SB.AppendLine("\tpublic static partial async Task<GameResource> LoadGameResourceFromTypeIDAndPath(ushort TypeID, string path)");
                LoadGameResourceFromTypeID_SB.AppendLine("\t{");
                LoadGameResourceFromTypeID_SB.AppendLine("\t\treturn TypeID switch");
                LoadGameResourceFromTypeID_SB.AppendLine("\t\t{");




                var getResourceTypeIDSB = new StringBuilder();

                getResourceTypeIDSB.AppendLine("\tpublic static partial ushort GetGameResourceTypeID(Type type)");
                getResourceTypeIDSB.AppendLine("\t{");
                getResourceTypeIDSB.AppendLine();



                var getResourceType_FROM_ID_SB = new StringBuilder();

                getResourceType_FROM_ID_SB.AppendLine("\tpublic static partial Type GetGameResourceTypeFromTypeID(ushort TypeID)");
                getResourceType_FROM_ID_SB.AppendLine("\t{");
                getResourceType_FROM_ID_SB.AppendLine("\t\treturn TypeID switch");
                getResourceType_FROM_ID_SB.AppendLine("\t\t{");




                var nonabstractResources = resourceTypes.Where(x => !x.IsAbstract).ToArray();




                for (int i = 0; i < nonabstractResources.Length; i++)
                {
                    INamedTypeSymbol? type = nonabstractResources[i];

                    var t_name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);



                    getResourceTypeIDSB.AppendLine(
                        $"\t\tif (type == typeof({t_name})) return {i};");

                    ConstructGameResourceFromGeneric_SB.AppendLine(
                        $"\t\tif (typeof(T) == typeof({t_name})) return (GameResource)(await {t_name}.Load(stream, key));");




                    getResourceType_FROM_ID_SB.AppendLine(
                        $"\t\t\t{i} => typeof({t_name}),");


                    ConstructGameResourceFromTypeID_SB.AppendLine(
                        $"\t\t\t{i} => (GameResource)(await {t_name}.Load(stream, key)),");

                    LoadGameResourceFromTypeID_SB.AppendLine(
                        $"\t\t\t{i} => (GameResource)(await Loading.LoadResource<{t_name}>(path)),");


                }



                ConstructGameResourceFromTypeID_SB.AppendLine("\t\t\t_ => throw new Exception(),");
                ConstructGameResourceFromTypeID_SB.AppendLine("\t\t};");
                ConstructGameResourceFromTypeID_SB.AppendLine("\t}");

                LoadGameResourceFromTypeID_SB.AppendLine("\t\t\t_ => throw new Exception(),");
                LoadGameResourceFromTypeID_SB.AppendLine("\t\t};");
                LoadGameResourceFromTypeID_SB.AppendLine("\t}");


                getResourceType_FROM_ID_SB.AppendLine($"\t\t\t{nonabstractResources.Length} => null,   //indicates no designated type");

                getResourceType_FROM_ID_SB.AppendLine("\t\t\t_ => throw new Exception(),");
                getResourceType_FROM_ID_SB.AppendLine("\t\t};");
                getResourceType_FROM_ID_SB.AppendLine("\t}");




                ConstructGameResourceFromGeneric_SB.AppendLine("\t\tthrow new Exception();");
                ConstructGameResourceFromGeneric_SB.AppendLine("\t}");


                getResourceTypeIDSB.AppendLine($"\t\tif (type == null) return {nonabstractResources.Length};   //indicates no designated type");
                getResourceTypeIDSB.AppendLine("\t\tthrow new Exception();");
                getResourceTypeIDSB.AppendLine("\t}");




                gameResourceSB.Append(ConstructGameResourceFromTypeID_SB);
                gameResourceSB.AppendLine();

                gameResourceSB.Append(LoadGameResourceFromTypeID_SB);
                gameResourceSB.AppendLine();

                gameResourceSB.Append(ConstructGameResourceFromGeneric_SB);
                gameResourceSB.AppendLine();

                gameResourceSB.Append(getResourceTypeIDSB);
                gameResourceSB.AppendLine();


                gameResourceSB.Append(getResourceType_FROM_ID_SB);
                gameResourceSB.AppendLine();




                gameResourceSB.Append("}");


                spc.AddSource("GameResource.g.cs", gameResourceSB.ToString());


            });
    }


}