using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class GameResourceStringTypeLoadGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static sym => sym != null)!;

        // Combine with compilation to get metadata for the base type
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
        {
            var (compilation, candidates) = source;

            var gameResourceType = compilation.GetTypeByMetadataName("Engine.Core.GameResource");
            if (gameResourceType == null)
                return;

            var resourceTypes = candidates!
                .Where(symbol => symbol != null && !symbol.IsAbstract && InheritsFrom(symbol!, gameResourceType)).Distinct(SymbolEqualityComparer.Default).Select(x=>(INamedTypeSymbol)x)
                .ToList()!;

            if (!resourceTypes.Any())
                return;

            var sourceText = GenerateCode(resourceTypes);
            spc.AddSource("SceneResource_Resources.g.cs", SourceText.From(sourceText, Encoding.UTF8));
        });
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
    {
        var current = symbol.BaseType;
        while (current != null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static string GenerateCode(IEnumerable<INamedTypeSymbol> resourceTypes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace Engine.Core;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using static Loading;");


        sb.AppendLine("");
        sb.AppendLine("public abstract partial class GameResource : RefCounted");
        sb.AppendLine("{");


        sb.AppendLine("        public static async Task<GameResource> ConstructResourceViaTypeName(string TypeName, byte[] bytes, string path) => TypeName switch");
        sb.AppendLine("        {");
        foreach (var type in resourceTypes)
        {
            sb.AppendLine($"         \"{type.Name}\" => (GameResource)await StaticVirtuals.Engine_Core_GameResource_Load<{type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(bytes, path),");
        }
        sb.AppendLine("            _ => throw new NotImplementedException()");
        sb.AppendLine("        };");




        sb.AppendLine("        public static async Task<GameResource> LoadResourceViaTypeName(string TypeName, string path) => TypeName switch");
        sb.AppendLine("        {");
        foreach (var type in resourceTypes)
        {
            sb.AppendLine($"         \"{type.Name}\" => (GameResource)await Loading.LoadResource<{type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(path),");
        }
        sb.AppendLine("            _ => throw new NotImplementedException()");
        sb.AppendLine("        };");




        sb.AppendLine("}");



        return sb.ToString();
    }
}
