using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis.CSharp;
using Engine.Attributes;

[Generator]
public sealed class GameResourceStaticReferenceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var compilationProvider = context.CompilationProvider;

        // --- Step 1: Collect all fields with the attribute ---
        var fieldSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is FieldDeclarationSyntax f && f.AttributeLists.Count > 0,
                static (ctx, _) =>
                {
                    var fieldDecl = (FieldDeclarationSyntax)ctx.Node;
                    var symbols = fieldDecl.Declaration.Variables
                        .Select(v => ctx.SemanticModel.GetDeclaredSymbol(v) as IFieldSymbol)
                        .Where(s => s != null)
                        .ToList();

                    var filtered = symbols
                        .Where(f => f!.GetAttributes()
                            .Any(a => a.AttributeClass?.Name == nameof(StaticGameResourceReferenceAttribute)))
                        .Select(x => (ISymbol)x)
                        .ToList();

                    return filtered.Count > 0 ? filtered : null;
                })
            .Where(s => s is not null)!;



        var collectedFields = fieldSymbols.SelectMany((list, ct) => ImmutableArray.CreateRange(list)).Collect();



        // --- Step 2: Generate source ---
        context.RegisterSourceOutput(compilationProvider.Combine(collectedFields), static (spc, source) =>
        {
            var (compilation, symbols) = source;

            var gameResourceType = compilation.GetTypeByMetadataName("Engine.GameResources.GameResource");

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("namespace Engine.Core;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("public static class StaticMetadata");
            sb.AppendLine("{");

            int accessorIndex = 0;

            // Only generate accessors if symbols exist
            if (symbols.Length > 0 && gameResourceType != null)
            {
                // Group by containing type
                var groups = symbols.GroupBy(s => s.ContainingType, SymbolEqualityComparer.Default)
                                    .OrderBy(g => g.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));

                foreach (var group in groups)
                {
                    foreach (var symbol in group)
                    {
                        var fieldSymbol = symbol as IFieldSymbol;
                        if (fieldSymbol == null) continue;

                        if (!fieldSymbol.IsStatic) continue;
                        if (fieldSymbol.ContainingType.IsStatic) continue;

                        var memberType = fieldSymbol.Type;
                        var conversion = compilation.ClassifyConversion(memberType, gameResourceType);
                        if (!conversion.Exists || !conversion.IsImplicit) continue;

                        var accessorName = $"Accessor{accessorIndex++}";
                        sb.AppendLine($"    [System.Runtime.CompilerServices.UnsafeAccessor(System.Runtime.CompilerServices.UnsafeAccessorKind.StaticField, Name = \"{fieldSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}\")]");
                        sb.AppendLine($"    private static extern ref {memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {accessorName}();");
                    }
                }
            }

            // Always generate the Load method
            sb.AppendLine();
            sb.AppendLine("    public static async Task LoadStaticResourceReferencesFor<T>()");
            sb.AppendLine("    {");
            sb.AppendLine("        //");
            sb.AppendLine("    }");

            // Always generate the Deload method
            sb.AppendLine();
            sb.AppendLine("    public static void DeloadStaticResourceReferencesFor<T>()");
            sb.AppendLine("    {");
            sb.AppendLine("        //");
            sb.AppendLine("    }");

            sb.AppendLine("}");

            spc.AddSource("StaticMetadata.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }
}
