using Engine.Attributes;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using static SourceGenCommon;




[Generator]
public sealed class GameObjectGlueGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (spc, compilation) =>
            {



                var allTypes = GetAllTypes(compilation.Assembly.GlobalNamespace);


                var gameObjectSB = new StringBuilder();






                gameObjectSB.AppendLine("// <auto-generated />");
                gameObjectSB.AppendLine("namespace Engine.Core;");
                gameObjectSB.AppendLine("using System;");
                gameObjectSB.AppendLine();

                gameObjectSB.AppendLine("public static partial class Parsing");
                gameObjectSB.AppendLine("{");






                //------------------------------------------------------------------------------------------



                var gameObjectBase =
                    compilation.GetTypeByMetadataName(
                        "Engine.Core.GameObject");


                var gameObjectTypes =
                    allTypes
                        .Where(t => DerivesFrom(t, gameObjectBase)).Concat([gameObjectBase])
                        .ToArray();





                var constructSB = new StringBuilder();
                var getobjTypeIDSB = new StringBuilder();


                constructSB.AppendLine("\tpublic static GameObject ConstructGameObjectFromTypeID(ushort TypeID)");
                constructSB.AppendLine("\t{");
                constructSB.AppendLine();
                constructSB.AppendLine("\t\treturn TypeID switch");
                constructSB.AppendLine("\t\t{");



                getobjTypeIDSB.AppendLine("\tpublic static ushort GetGameObjectTypeID(Type type)");
                getobjTypeIDSB.AppendLine("\t{");
                getobjTypeIDSB.AppendLine();


                var nonabstract = gameObjectTypes.Where(x => !x.IsAbstract).ToArray();


                for (int i = 0; i < nonabstract.Length; i++)
                {
                    INamedTypeSymbol? type = nonabstract[i];

                    constructSB.AppendLine($"\t\t\t{i} => new {type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}(),");

                    getobjTypeIDSB.AppendLine($"\t\tif (type == typeof({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})) return {i};");
                }




                getobjTypeIDSB.AppendLine("\t\tthrow new Exception();");
                getobjTypeIDSB.AppendLine();

                getobjTypeIDSB.AppendLine("\t}");



                constructSB.AppendLine("\t\t\t_ => throw new Exception(),");
                constructSB.AppendLine("\t\t};");
                constructSB.AppendLine();
                constructSB.AppendLine("\t}");




                gameObjectSB.Append(getobjTypeIDSB);
                gameObjectSB.AppendLine();
                gameObjectSB.Append(constructSB);


                gameObjectSB.AppendLine("}");



                gameObjectSB.AppendLine();
                gameObjectSB.AppendLine();


                //------------------------------------------------------------------------------------------


                spc.AddSource("GameObject.g.cs", gameObjectSB.ToString());



            });
    }

}