using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;




[Generator]
public sealed class GlueGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (spc, compilation) =>
            {



                var allTypes = GetAllTypes(compilation.Assembly.GlobalNamespace);


                var gameObjectSB = new StringBuilder();


                var gameResourceSB = new StringBuilder();




                gameResourceSB.AppendLine("// <auto-generated />");
                gameResourceSB.AppendLine("namespace Engine.Core;");
                gameResourceSB.AppendLine("using System;");
                gameResourceSB.AppendLine();

                gameResourceSB.AppendLine("public static partial class Parsing");
                gameResourceSB.AppendLine("{");





                gameObjectSB.Append(gameResourceSB);




                //------------------------------------------------------------------------------------------



                var gameObjectBase =
                    compilation.GetTypeByMetadataName(
                        "Engine.Core.GameObject");


                var gameObjectTypes =
                    allTypes
                        .Where(t => DerivesFrom(t, gameObjectBase)).Concat([gameObjectBase])
                        .ToArray();



                foreach (var t in gameObjectTypes)
                {
                    foreach (var c in t.InstanceConstructors)
                    {
                        if (c.Parameters.Count() != 0)
                        {
                            spc.ReportDiagnostic(Diagnostic.Create(
                               new DiagnosticDescriptor(
                                   "GLUE03",
                                   "GameObject constructor",
                                   "GameObject types cannot have constructor parameters. Use Init instead",
                                   "GameObject",
                                   DiagnosticSeverity.Error,
                                   true),
                               c.Locations.FirstOrDefault()));

                            continue;
                        }
                    }
                }




                var constructSB = new StringBuilder();
                var getobjTypeIDSB = new StringBuilder();


                constructSB.AppendLine("\tpublic static GameObject ConstructGameObjectFromTypeID(ushort TypeID)");
                constructSB.AppendLine("\t{");
                constructSB.AppendLine();
                constructSB.AppendLine("\t\treturn TypeID switch");
                constructSB.AppendLine("\t\t{");



                getobjTypeIDSB.AppendLine("#if DEBUG");
                getobjTypeIDSB.AppendLine("\tpublic static ushort GetGameObjectTypeID(Type type)");
                getobjTypeIDSB.AppendLine("\t{");
                getobjTypeIDSB.AppendLine();


                var nonabstract = gameObjectTypes.Where(x => !x.IsAbstract).ToArray();


                for (int i = 0; i < nonabstract.Length; i++)
                {
                    INamedTypeSymbol? type = nonabstract[i];

                    constructSB.AppendLine($"\t\t\t{i} => new {type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}(),");

                    getobjTypeIDSB.AppendLine($"\t\tif (type == typeof({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})) return {i};");
                }




                getobjTypeIDSB.AppendLine("\t\tthrow new Exception();");
                getobjTypeIDSB.AppendLine();

                getobjTypeIDSB.AppendLine("\t}");
                getobjTypeIDSB.AppendLine("#endif");



                constructSB.AppendLine("\t\t\t_ => throw new Exception(),");
                constructSB.AppendLine("\t\t};");
                constructSB.AppendLine();
                constructSB.AppendLine("\t}");










                var callInitForSB = new StringBuilder();




                callInitForSB.AppendLine("\tpublic static void CallInitFor(GameObject obj, Dictionary<string, object> args)");
                callInitForSB.AppendLine("\t{");

                callInitForSB.AppendLine("\t\tvar objType = obj.GetType();");

                callInitForSB.AppendLine();






                for (int i = 0; i < gameObjectTypes.Length; i++)
                {

                    INamedTypeSymbol? type = gameObjectTypes[i];

                    var initcandidates = type
                                    .GetMembers("Init")
                                    .OfType<IMethodSymbol>();


                    var initMethod = initcandidates.FirstOrDefault();



                    //initial checks

                    if (initcandidates.Count() != 1)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "GLUE00",
                                "Erroneous Init method setup",
                                "Each GameObject type must have 1 Init method.",
                                "GameObject",
                                DiagnosticSeverity.Error,
                                true), 
                            type.Locations.FirstOrDefault()));

                        continue;
                    }

                    if (initMethod.IsVirtual || initMethod.IsAbstract || initMethod.IsStatic)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "GLUE01",
                                "Erroneous Init method setup",
                                "Each GameObject's Init method must be non-virtual, non-abstract, and non-static.",
                                "GameObject",
                                DiagnosticSeverity.Error,
                                true),
                            type.Locations.FirstOrDefault()));

                        continue;
                    }



                    var basecall = initMethod.ContainingType.BaseType
                            .GetMembers("Init")
                            .OfType<IMethodSymbol>()
                            .FirstOrDefault();


                    if (!SymbolEqualityComparer.Default.Equals(
                        type,
                        gameObjectBase))
                    {

                        if (basecall == null)
                            continue;


                        if (!CallsMethod(compilation, initMethod, basecall))

                        {
                            spc.ReportDiagnostic(Diagnostic.Create(
                               new DiagnosticDescriptor(
                                   "GLUE02",
                                   "Erroneous Init method setup",
                                   "Each GameObject's Init method must call it's direct base Init method.",
                                   "GameObject",
                                   DiagnosticSeverity.Error,
                                   true),
                               type.Locations.FirstOrDefault()));


                            continue;
                        }
                    }

                    



                    callInitForSB.AppendLine();
                    callInitForSB.AppendLine();
                    callInitForSB.AppendLine($"//-------------------------------------- [ {type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} ] --------------------------------------");
                    callInitForSB.AppendLine();
                    callInitForSB.AppendLine();


                    callInitForSB.AppendLine($"\t\tif (objType == typeof({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}))");
                    callInitForSB.AppendLine("\t\t{");


                    List<string> args = new();

                    for (int i1 = 0; i1 < initMethod.Parameters.Length; i1++)
                    {

                        callInitForSB.AppendLine();


                        IParameterSymbol? param = initMethod.Parameters[i1];


                        var valname = $"val_{type.Name}_{param.Name}";
                        var valGet = $"val_{type.Name}_{param.Name}_get";


                        callInitForSB.AppendLine($"\t\t\t{param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {valname};");


                        callInitForSB.AppendLine($"\t\t\tif (args != null && args.TryGetValue(\"{param.Name}\", out var {valGet}))");
                        callInitForSB.AppendLine($"\t\t\t\t{valname} = ({param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}){valGet};");


                        callInitForSB.AppendLine($"\t\t\telse");
                        
                        if (param.HasExplicitDefaultValue)
                        {
                            if (param.ExplicitDefaultValue is null)
                            {
                                if (param.Type.IsReferenceType || param.Type.NullableAnnotation == NullableAnnotation.Annotated)
                                {
                                    callInitForSB.AppendLine($"\t\t\t\t{valname} = null;");
                                }
                                else
                                {
                                    callInitForSB.AppendLine($"\t\t\t\t{valname} = default;");
                                }
                            }
                            else
                            {
                                callInitForSB.AppendLine($"\t\t\t\t{valname} = {FormatLiteral(param.ExplicitDefaultValue, param.Type)};");
                            }
                        }
                        else
                        {
                            callInitForSB.AppendLine($"\t\t\t\tthrow new ArgumentNullException();    //required argument '{param.Name}' is missing");
                        }





                        args.Add(valname);




                    }


                    callInitForSB.AppendLine();
                    callInitForSB.AppendLine();


                    callInitForSB.AppendLine($"\t\t\t(({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})obj).Init({(string.Join(", ", args))});");

                    callInitForSB.AppendLine();


                    callInitForSB.AppendLine($"\t\t\treturn;");



                    callInitForSB.AppendLine("\t\t}");




                }


                callInitForSB.AppendLine();
                callInitForSB.AppendLine();
                callInitForSB.AppendLine("\t\tthrow new Exception();");


                callInitForSB.AppendLine();
                callInitForSB.AppendLine();


                callInitForSB.AppendLine("\t}");


                gameObjectSB.Append(getobjTypeIDSB);
                gameObjectSB.AppendLine();
                gameObjectSB.Append(constructSB);

                gameObjectSB.AppendLine();
                gameObjectSB.AppendLine();
                gameObjectSB.AppendLine();

                gameObjectSB.Append(callInitForSB);



                gameObjectSB.AppendLine("}");






                //------------------------------------------------------------------------------------------




                var resourceBase =
                    compilation.GetTypeByMetadataName(
                        "Engine.Core.GameResource");


                var resourceTypes =
                    allTypes
                        .Where(t => DerivesFrom(t, resourceBase))
                        .ToArray();








                var ConstructGameResourceFromGeneric_SB = new StringBuilder();

                ConstructGameResourceFromGeneric_SB.AppendLine("\tpublic static async Task<GameResource> ConstructGameResourceFromGeneric<T>(Loading.AssetByteStream stream, string key) where T : GameResource");
                ConstructGameResourceFromGeneric_SB.AppendLine("\t{");
                ConstructGameResourceFromGeneric_SB.AppendLine(); 



                var ConstructGameResourceFromTypeID_SB = new StringBuilder();

                ConstructGameResourceFromTypeID_SB.AppendLine("\tpublic static async Task<GameResource> ConstructGameResourceFromTypeID(ushort TypeID, Loading.AssetByteStream stream, string key)");
                ConstructGameResourceFromTypeID_SB.AppendLine("\t{");
                ConstructGameResourceFromTypeID_SB.AppendLine();
                ConstructGameResourceFromTypeID_SB.AppendLine("\t\treturn TypeID switch");
                ConstructGameResourceFromTypeID_SB.AppendLine("\t\t{");



                var LoadGameResourceFromTypeID_SB = new StringBuilder();

                LoadGameResourceFromTypeID_SB.AppendLine("\tpublic static async Task<GameResource> LoadGameResourceFromTypeID(ushort TypeID, string path)");
                LoadGameResourceFromTypeID_SB.AppendLine("\t{");
                LoadGameResourceFromTypeID_SB.AppendLine("\t\treturn TypeID switch");
                LoadGameResourceFromTypeID_SB.AppendLine("\t\t{");




                var getResourceTypeIDSB = new StringBuilder();

                getResourceTypeIDSB.AppendLine("#if DEBUG");
                getResourceTypeIDSB.AppendLine("\tpublic static ushort GetGameResourceTypeID(Type type)");
                getResourceTypeIDSB.AppendLine("\t{");
                getResourceTypeIDSB.AppendLine();



                var getResourceType_FROM_ID_SB = new StringBuilder();

                getResourceType_FROM_ID_SB.AppendLine("\tpublic static Type GetGameResourceTypeFromTypeID(ushort TypeID)");
                getResourceType_FROM_ID_SB.AppendLine("\t{");
                getResourceType_FROM_ID_SB.AppendLine("\t\treturn TypeID switch");
                getResourceType_FROM_ID_SB.AppendLine("\t\t{");




                var nonabstractResources = resourceTypes.Where(x => !x.IsAbstract).ToArray();




                for (int i = 0; i < nonabstractResources.Length; i++)
                {
                    INamedTypeSymbol? type = nonabstractResources[i];

                    var t_name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);



                    getResourceTypeIDSB.AppendLine(
                        $"\t\tif (type == typeof({t_name})) return {i};");

                    ConstructGameResourceFromGeneric_SB.AppendLine(
                        $"\t\tif (typeof(T) == typeof({t_name})) return (GameResource)(await {t_name}.Load(stream, key));");




                    getResourceType_FROM_ID_SB.AppendLine(
                        $"\t\t\t{i} => typeof({t_name}),");


                    ConstructGameResourceFromTypeID_SB.AppendLine(
                        $"\t\t\t{i} => (GameResource)(await {t_name}.Load(stream, key)),");

                    LoadGameResourceFromTypeID_SB.AppendLine(
                        $"\t\t\t{i} => (GameResource)(await Loading.LoadResource<{t_name}>(path)),");


                }



                ConstructGameResourceFromTypeID_SB.AppendLine("\t\t\t_ => throw new Exception(),");
                ConstructGameResourceFromTypeID_SB.AppendLine("\t\t};");
                ConstructGameResourceFromTypeID_SB.AppendLine("\t}");

                LoadGameResourceFromTypeID_SB.AppendLine("\t\t\t_ => throw new Exception(),");
                LoadGameResourceFromTypeID_SB.AppendLine("\t\t};");
                LoadGameResourceFromTypeID_SB.AppendLine("\t}");


                getResourceType_FROM_ID_SB.AppendLine($"\t\t\t{nonabstractResources.Length} => null,   //indicates no designated type");

                getResourceType_FROM_ID_SB.AppendLine("\t\t\t_ => throw new Exception(),");
                getResourceType_FROM_ID_SB.AppendLine("\t\t};");
                getResourceType_FROM_ID_SB.AppendLine("\t}");




                ConstructGameResourceFromGeneric_SB.AppendLine("\t\tthrow new Exception();");
                ConstructGameResourceFromGeneric_SB.AppendLine("\t}");


                getResourceTypeIDSB.AppendLine($"\t\tif (type == null) return {nonabstractResources.Length};   //indicates no designated type");
                getResourceTypeIDSB.AppendLine("\t\tthrow new Exception();");
                getResourceTypeIDSB.AppendLine("\t}");
                getResourceTypeIDSB.AppendLine("#endif");




                gameResourceSB.Append(ConstructGameResourceFromTypeID_SB);
                gameResourceSB.AppendLine();

                gameResourceSB.Append(LoadGameResourceFromTypeID_SB);
                gameResourceSB.AppendLine();

                gameResourceSB.Append(ConstructGameResourceFromGeneric_SB);
                gameResourceSB.AppendLine();

                gameResourceSB.Append(getResourceTypeIDSB);
                gameResourceSB.AppendLine();


                gameResourceSB.Append(getResourceType_FROM_ID_SB);
                gameResourceSB.AppendLine();




                gameResourceSB.Append("}");


                spc.AddSource("GameObject.g.cs", gameObjectSB.ToString());


                spc.AddSource("GameResource.g.cs", gameResourceSB.ToString());





            });
    }









    static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
    {
        foreach (var member in ns.GetMembers())
        {
            if (member is INamespaceSymbol nested)
            {
                foreach (var t in GetAllTypes(nested))
                    yield return t;
            }
            else if (member is INamedTypeSymbol type)
            {
                yield return type;
            }
        }
    }

    static bool DerivesFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        for (var t = type.BaseType; t != null; t = t.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(t, baseType))
                return true;
        }

        return false;
    }



    static string FormatLiteral(
    object? value,
    ITypeSymbol targetType)
    {
        if (value == null)
            return "null";

        // Enum constants
        if (targetType.TypeKind == TypeKind.Enum)
        {
            var enumType =
                targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            return $"{enumType}.{value}";
        }

        return value switch
        {
            string s => $"\"{s}\"",
            char c => $"'{c}'",
            bool b => b ? "true" : "false",

            float f => f.ToString("R") + "f",
            double d => d.ToString("R"),
            long l => l.ToString() + "L",
            ulong ul => ul.ToString() + "UL",
            uint ui => ui.ToString() + "u",

            byte or sbyte or short or ushort or int
                => value.ToString()!,

            _ => $"default({targetType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})"
        };
    }


    static bool CallsMethod(
        Compilation compilation,
        IMethodSymbol caller,
        IMethodSymbol target)
    {
        foreach (var syntaxRef in caller.DeclaringSyntaxReferences)
        {
            var syntaxTree = syntaxRef.SyntaxTree;
            var semanticModel = compilation.GetSemanticModel(syntaxTree);

            if (syntaxRef.GetSyntax() is not MethodDeclarationSyntax methodDecl)
                continue;

            var body = (SyntaxNode?)methodDecl.Body ?? methodDecl.ExpressionBody;
            if (body is null)
                continue;

            foreach (var invocation in body.DescendantNodes()
                         .OfType<InvocationExpressionSyntax>())
            {
                var symbolInfo = semanticModel.GetSymbolInfo(invocation);
                if (symbolInfo.Symbol is not IMethodSymbol invoked)
                    continue;

                if (SymbolEqualityComparer.Default.Equals(
                    invoked.OriginalDefinition,
                    target.OriginalDefinition))
                {
                    return true;
                }
            }
        }

        return false;
    }


}