using Engine.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

[Generator]
public sealed class PartialDefaultReturnGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var methods = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => s is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                static (ctx, _) =>
                {
                    var method = (MethodDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(method) as IMethodSymbol;
                    if (symbol == null)
                        return null;

                    if (!symbol.IsPartialDefinition)
                        return null;

                    if (symbol.PartialImplementationPart != null)
                        return null;

                    foreach (var attr in symbol.GetAttributes())
                    {
                        if (attr.AttributeClass?.Name == nameof(PartialDefaultReturnAttribute))
                            return symbol;
                    }

                    return null;

                })
            .Where(static m => m != null)!;

        var collected = methods.Collect();

        context.RegisterSourceOutput(collected, static (spc, methods) =>
        {
            Generate(spc, methods);
        });
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<IMethodSymbol> methods)
    {
        if (methods.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var namespaceGroup in methods.GroupBy(m => m.ContainingNamespace, SymbolEqualityComparer.Default))
        {
            EmitNamespace(sb, (INamespaceSymbol)namespaceGroup.Key, namespaceGroup.ToList());
        }

        context.AddSource(
            "PartialDefaultReturn.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitNamespace(
        StringBuilder sb,
        INamespaceSymbol ns,
        List<IMethodSymbol> methods)
    {
        if (!ns.IsGlobalNamespace)
        {
            sb.Append("namespace ").Append(ns.ToDisplayString()).AppendLine();
            sb.AppendLine("{");
        }

        var byRootType = methods
            .GroupBy(m => GetTypeChain(m.ContainingType).Last(), SymbolEqualityComparer.Default);

        foreach (var typeGroup in byRootType)
        {
            EmitTypeRecursive(sb, (INamedTypeSymbol)typeGroup.Key, typeGroup.ToList(), 1);
        }

        if (!ns.IsGlobalNamespace)
        {
            sb.AppendLine("}");
        }
    }

    private static void EmitTypeRecursive(
        StringBuilder sb,
        INamedTypeSymbol type,
        List<IMethodSymbol> methods,
        int indent)
    {
        var indentStr = new string(' ', indent * 4);

        sb.Append(indentStr);
        sb.Append(GetTypeDeclaration(type));
        sb.AppendLine();
        sb.Append(indentStr).AppendLine("{");

        var directMethods = methods
            .Where(m => SymbolEqualityComparer.Default.Equals(m.ContainingType, type))
            .ToList();

        foreach (var method in directMethods)
        {
            EmitMethod(sb, method, indent + 1);
        }

        var nestedGroups = methods
            .Where(m => m.ContainingType.ContainingType != null &&
                        SymbolEqualityComparer.Default.Equals(m.ContainingType.ContainingType, type))
            .GroupBy(m => m.ContainingType, SymbolEqualityComparer.Default);

        foreach (var nested in nestedGroups)
        {
            EmitTypeRecursive(sb, (INamedTypeSymbol)nested.Key, nested.ToList(), indent + 1);
        }

        sb.Append(indentStr).AppendLine("}");
    }

    private static void EmitMethod(StringBuilder sb, IMethodSymbol method, int indent)
    {
        var indentStr = new string(' ', indent * 4);

        sb.Append(indentStr);
        sb.Append(GetMethodModifiers(method));
        sb.Append(method.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        sb.Append(' ');
        sb.Append(method.Name);

        if (method.IsGenericMethod)
        {
            sb.Append('<')
              .Append(string.Join(", ", method.TypeParameters.Select(p => p.Name)))
              .Append('>');
        }

        sb.Append('(');
        sb.Append(string.Join(", ",
            method.Parameters.Select(p =>
                $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {p.Name}")));
        sb.Append(')');

        foreach (var tp in method.TypeParameters)
        {
            EmitTypeParameterConstraints(sb, tp);
        }

        sb.AppendLine();

        if (method.ReturnsVoid)
        {
            sb.Append(indentStr).AppendLine("{");
            sb.Append(indentStr).AppendLine("}");
        }
        else
        {
            sb.Append(indentStr).AppendLine("=> default;");
        }
    }

    private static string GetTypeDeclaration(INamedTypeSymbol type)
    {
        var sb = new StringBuilder();

        sb.Append(GetAccessibility(type));
        

        if (type.IsStatic) sb.Append("static ");
        if (type.IsAbstract && type.TypeKind == TypeKind.Class) sb.Append("abstract ");
        if (type.IsSealed && type.TypeKind == TypeKind.Class) sb.Append("sealed ");
        if (type.IsReadOnly) sb.Append("readonly ");
        if (type.IsRefLikeType) sb.Append("ref ");

        sb.Append("partial ");


        sb.Append(type.TypeKind switch
        {
            TypeKind.Class => "class ",
            TypeKind.Struct => type.IsRecord ? "record struct " : "struct ",
            TypeKind.Interface => "interface ",
            _ => "class "
        });

        sb.Append(type.Name);

        if (type.TypeParameters.Length > 0)
        {
            sb.Append('<')
              .Append(string.Join(", ", type.TypeParameters.Select(p => p.Name)))
              .Append('>');
        }

        var bases = type.BaseType != null && type.BaseType.SpecialType != SpecialType.System_Object
            ? new[] { type.BaseType }
            : Enumerable.Empty<ITypeSymbol>();

        var interfaces = type.Interfaces;

        var baseList = bases.Concat(interfaces).ToList();
        if (baseList.Count > 0)
        {
            sb.Append(" : ");
            sb.Append(string.Join(", ",
                baseList.Select(b => b.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))));
        }

        foreach (var tp in type.TypeParameters)
        {
            EmitTypeParameterConstraints(sb, tp);
        }

        return sb.ToString();
    }

    private static void EmitTypeParameterConstraints(StringBuilder sb, ITypeParameterSymbol tp)
    {
        var constraints = new List<string>();

        if (tp.HasReferenceTypeConstraint) constraints.Add("class");
        if (tp.HasValueTypeConstraint) constraints.Add("struct");

        constraints.AddRange(tp.ConstraintTypes.Select(t =>
            t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));

        if (tp.HasConstructorConstraint) constraints.Add("new()");

        if (constraints.Count > 0)
        {
            sb.Append(" where ").Append(tp.Name).Append(" : ");
            sb.Append(string.Join(", ", constraints));
        }
    }

    private static string GetAccessibility(ISymbol symbol) =>
        symbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public ",
            Accessibility.Internal => "internal ",
            Accessibility.Protected => "protected ",
            Accessibility.ProtectedAndInternal => "protected internal ",
            Accessibility.ProtectedOrInternal => "private protected ",
            _ => ""
        };

    private static string GetMethodModifiers(IMethodSymbol method)
    {
        var sb = new StringBuilder();

        sb.Append(GetAccessibility(method));
        if (method.IsStatic) sb.Append("static ");
        if (method.IsAbstract) sb.Append("abstract ");
        if (method.IsVirtual && !method.IsAbstract) sb.Append("virtual ");
        if (method.IsOverride) sb.Append("override ");
        sb.Append("partial ");

        return sb.ToString();
    }

    private static IEnumerable<INamedTypeSymbol> GetTypeChain(INamedTypeSymbol type)
    {
        var stack = new Stack<INamedTypeSymbol>();
        for (var t = type; t != null; t = t.ContainingType)
            stack.Push(t);
        return stack;
    }
}
