using Engine.Attributes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;




[Generator]
public sealed class SerializationGenerator : IIncrementalGenerator
{

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var attributeTypes1 = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                typeof(BinarySerializableTypeAttribute).FullName,          
                static (node, _) => true,           
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);


        var assemblyAttributes =
            context.CompilationProvider
            .SelectMany((compilation, _) =>
            {
                return compilation.Assembly
                    .GetAttributes()
                    .Where(a => a.AttributeClass?.ToDisplayString() == typeof(BinarySerializableTypeAssemblyLevelAttribute).FullName)
                    .Select(a =>
                    {
                        var arg = a.ConstructorArguments[0];
                        return arg.Value as ITypeSymbol;
                    })
                    .Where(t => t is not null)!;
            }).Collect();





        var deserializeTypes =
            context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) =>
                        node is InvocationExpressionSyntax,
                    static (ctx, _) =>
                    {
                        var invocation =
                            (InvocationExpressionSyntax)ctx.Node;

                        if (ctx.SemanticModel
                                .GetSymbolInfo(invocation).Symbol
                            is not IMethodSymbol method)
                            return null;

                        if (!method.IsGenericMethod)
                            return null;

                        if (method.OriginalDefinition.ToDisplayString() != "Engine.Core.Parsing.DeserializeKnownType<T>")
                            return null;


                        return method.TypeArguments[0];
                    })
                .Where(static t => t is not null)!;




        var attribute1Collected = attributeTypes1.Collect();
        var deserializeCollected = deserializeTypes.Collect();



        var allTypes =
            attribute1Collected
                .Combine(deserializeCollected)
                .Select(static (pair, _) =>
                {
                    var (a, b) = pair;

                    return a
                        .Concat(b)
                        .Distinct(SymbolEqualityComparer.Default)
                        .Cast<ITypeSymbol>();
                });




        context.RegisterSourceOutput(
            allTypes.Combine(assemblyAttributes).Combine(context.CompilationProvider),
            static (spc, source) =>
            {
                var sb = new StringBuilder();



                sb.AppendLine("// <auto-generated />");
                sb.AppendLine("namespace Engine.Core;");
                sb.AppendLine("using System;");
                sb.AppendLine("using System.Runtime.CompilerServices;");
                sb.AppendLine("using System.Runtime.InteropServices;");
                sb.AppendLine("using System.Text;");
                sb.AppendLine();

                sb.AppendLine("public static partial class Parsing");
                sb.AppendLine("{");






                static ITypeSymbol GetDeserializeOverriderType(ITypeSymbol t)
                    => t.Interfaces.FirstOrDefault(x => x.OriginalDefinition.ToDisplayString() == "Engine.Core.ISerializeOverrider<TFrom>")?.TypeArguments[0];




                static bool CanBeBlit(ITypeSymbol type)
                    =>
                    type.IsUnmanagedType
                    &&
                    !type.GetMembers()
                        .OfType<IFieldSymbol>()
                            .Any(f => !f.IsStatic && f.GetAttributes()
                                .Any(a => a.AttributeClass?.Name == nameof(NonSerializedAttribute)));




                static bool IsDictionary(ITypeSymbol type, out ITypeSymbol key, out ITypeSymbol value)
                {
                    if (type is INamedTypeSymbol named)
                    {
                        var dictInterface = named.AllInterfaces
                            .FirstOrDefault(i =>
                                i.OriginalDefinition.ToDisplayString() ==
                                "System.Collections.Generic.IDictionary<TKey, TValue>");

                        if (dictInterface != null)
                        {
                            key = dictInterface.TypeArguments[0];
                            value = dictInterface.TypeArguments[1];
                            return true;
                        }
                    }

                    key = null;
                    value = null;
                    return false;
                }




                var allTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

                void EvaluateAndAdd(ITypeSymbol type)
                {
                    if (!allTypes.Add(type))
                        return;


                    if (GetDeserializeOverriderType(type) != null)
                    {
                        EvaluateAndAdd(GetDeserializeOverriderType(type));
                        return;
                    }


                    if (type is IArrayTypeSymbol arr)
                        EvaluateAndAdd(arr.ElementType);


                    if (IsDictionary(type, out var key, out var value))
                    {
                        EvaluateAndAdd(key);
                        EvaluateAndAdd(value);
                    }


                    if (type.TypeKind == TypeKind.Enum)
                        EvaluateAndAdd(((INamedTypeSymbol)type).EnumUnderlyingType);



                    if (type is INamedTypeSymbol named &&
                            type.TypeKind != TypeKind.Enum)
                    {
                        foreach (var member in named.GetMembers())
                        {
                            if (member is IFieldSymbol field && !field.IsStatic && !field.IsReadOnly && !field.GetAttributes().Any(x=>x.AttributeClass.Name == nameof(NonSerializedAttribute)))
                                EvaluateAndAdd(field.Type);
                        }
                    }

                }



                foreach (var t in source.Left.Left)
                    EvaluateAndAdd(t);

                foreach (var t in source.Left.Right)
                    EvaluateAndAdd(t);


                
                if (allTypes.Any(x => x.SpecialType == SpecialType.System_String))
                    EvaluateAndAdd(source.Right.CreateArrayTypeSymbol(source.Right.GetSpecialType(SpecialType.System_Byte)));






                var types = allTypes
                    .OrderBy(t => t.ToDisplayString())
                    .ToArray();






                // --------------------------------------------------------------------




                var serialize = new StringBuilder();

                var deserializeUnknown = new StringBuilder();

                var deserializeKnown = new StringBuilder();

                




                serialize.AppendLine("\tpublic static byte[] SerializeType(object value, bool writeTypeID)");
                serialize.AppendLine("\t{");

                deserializeKnown.AppendLine("\tpublic static unsafe T DeserializeKnownType<T>(this Stream reader, object context = null)");
                deserializeKnown.AppendLine("\t{");

                deserializeUnknown.AppendLine("\tpublic static object DeserializeUnknownType(this Stream reader, object context = null)");
                deserializeUnknown.AppendLine("\t{");
                deserializeUnknown.AppendLine("\t\tvar id = reader.DeserializeKnownType<ushort>(context);");
                deserializeUnknown.AppendLine("\t\tswitch (id)");
                deserializeUnknown.AppendLine("\t\t{");





                for (int i = 0; i < types.Length; i++)
                {

                    ITypeSymbol t = types[i];
                    var symname = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    deserializeUnknown.AppendLine($"\t\t\tcase {i}:");
                    deserializeUnknown.AppendLine($"\t\t\t\treturn reader.DeserializeKnownType<{symname}>(context);");

                    deserializeKnown.AppendLine($"\t\tif (typeof(T) == typeof({symname}))");
                    deserializeKnown.AppendLine("\t\t{");


                    serialize.AppendLine($"\t\tif (value.GetType() == typeof({symname}))");
                    serialize.AppendLine("\t\t{");
                    serialize.AppendLine($"\t\t\tvar value_cast_{i} = ({symname})value;");
                    serialize.AppendLine($"\t\t\tList<byte> temp_var_{i} = new();");




                    // ARRAY

                    if (t is IArrayTypeSymbol arr)
                    {
                        var elementName = arr.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                        deserializeKnown.AppendLine($"\t\t\tvar len_{i} = ReadVarUInt64(reader);");
                        deserializeKnown.AppendLine($"\t\t\tvar arr_{i} = new {elementName}[len_{i}];");


                        serialize.AppendLine($"\t\t\ttemp_var_{i}.AddRange(WriteVarUInt64((ulong)value_cast_{i}.Length));");


                        if (CanBeBlit(arr.ElementType))
                        {
                            deserializeKnown.AppendLine($"\t\t\tSpan<byte> span_{i} = MemoryMarshal.AsBytes(arr_{i}.AsSpan());");
                            deserializeKnown.AppendLine($"\t\t\treader.ReadExactly(span_{i});");

                            serialize.AppendLine(
                                $"\t\t\ttemp_var_{i}.AddRange(" +
                                $"MemoryMarshal.AsBytes(value_cast_{i}.AsSpan()));");
                        }
                        else
                        {
                            deserializeKnown.AppendLine($"\t\t\tfor (ulong j = 0; j < len_{i}; j++)");
                            deserializeKnown.AppendLine($"\t\t\t\tarr_{i}[j] = reader.DeserializeKnownType<{elementName}>(reader);");


                            serialize.AppendLine($"\t\t\tfor (int i{i} = 0; i{i} < value_cast_{i}.Length; i{i}++)");
                            serialize.AppendLine($"\t\t\t\ttemp_var_{i}.AddRange(SerializeType(value_cast_{i}[i{i}], false));");

                        }

                        deserializeKnown.AppendLine($"\t\t\treturn Unsafe.As<{symname}, T>(ref arr_{i});");




                    }




                    // DICTIONARY

                    else if (IsDictionary(t, out var key, out var value))
                    {
                        var keyName = key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        var valueName = value.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                        deserializeKnown.AppendLine($"\t\t\tvar count_{i} = ReadVarUInt64(reader);");
                        deserializeKnown.AppendLine($"\t\t\tvar dict_{i} = new {symname}((int)count_{i});");

                        deserializeKnown.AppendLine($"\t\t\tfor (ulong j = 0; j < count_{i}; j++)");
                        deserializeKnown.AppendLine($"\t\t\t\tdict_{i}[reader.DeserializeKnownType<{keyName}>(context)] = reader.DeserializeKnownType<{valueName}>(context);");

                        deserializeKnown.AppendLine($"\t\t\treturn Unsafe.As<{symname}, T>(ref dict_{i});");


                        serialize.AppendLine($"\t\t\ttemp_var_{i}.AddRange(WriteVarUInt64((ulong)value_cast_{i}.Count));");
                        serialize.AppendLine($"\t\t\tforeach (var kv in value_cast_{i})");
                        serialize.AppendLine("\t\t\t{");
                        serialize.AppendLine($"\t\t\t\ttemp_var_{i}.AddRange(SerializeType(kv.Key, false));");
                        serialize.AppendLine($"\t\t\t\ttemp_var_{i}.AddRange(SerializeType(kv.Value, false));");
                        serialize.AppendLine("\t\t\t}");
                    }




                    // STRING

                    else if (t.SpecialType == SpecialType.System_String)
                    {
                        deserializeKnown.AppendLine($"\t\t\tvar str_{i} = Encoding.UTF8.GetString(reader.DeserializeKnownType<byte[]>(context));");
                        
                        deserializeKnown.AppendLine($"\t\t\treturn Unsafe.As<string, T>(ref str_{i});");

                        serialize.AppendLine($"\t\t\ttemp_var_{i}.AddRange(SerializeType(Encoding.UTF8.GetBytes(value_cast_{i}), false));");
                    }




                    // IMPLEMENTS OWN DESERIALIZATION

                    else if (GetDeserializeOverriderType(t) != null)
                    {
                        var from = GetDeserializeOverriderType(t).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                        deserializeKnown.AppendLine($"\t\t\tvar temp_var_2_{i} = {symname}.Deserialize(reader.DeserializeKnownType<{from}>(context), context);");
                        deserializeKnown.AppendLine($"\t\t\treturn Unsafe.As<{symname}, T>(ref temp_var_2_{i});");
                    }




                    // BLITTABLE      (UNMANAGED)

                    else if (CanBeBlit(t))
                    {
                        deserializeKnown.AppendLine($"\t\t\tSpan<byte> buf_{i} = stackalloc byte[sizeof({symname})];");
                        deserializeKnown.AppendLine($"\t\t\treader.ReadExactly(buf_{i});");
                        deserializeKnown.AppendLine($"\t\t\t{symname} value_{i};");

                        deserializeKnown.AppendLine($"\t\t\tfixed (byte* p_{i} = buf_{i})");
                        deserializeKnown.AppendLine($"\t\t\t\tvalue_{i} = *({symname}*)p_{i};");

                        deserializeKnown.AppendLine($"\t\t\treturn Unsafe.As<{symname}, T>(ref value_{i});");


                        serialize.AppendLine(
                            $"\t\t\ttemp_var_{i}.AddRange(MemoryMarshal.AsBytes(" +
                            $"MemoryMarshal.CreateSpan(ref value_cast_{i}, 1)));");
                    }




                    // NON-BLITTABLE   (MANAGED OR PARTICULAR)

                    else
                    {
                        deserializeKnown.AppendLine($"\t\t\t{symname} temp_var_{i} = new();");

                        foreach (var member in t.GetMembers())
                        {
                            if (member.DeclaredAccessibility == Accessibility.Public && !member.IsStatic)
                            {
                                void commit(string name, ITypeSymbol type)
                                {
                                    deserializeKnown.AppendLine($"\t\t\ttemp_var_{i}.{name} = reader.DeserializeKnownType<{type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(context);");

                                    serialize.AppendLine($"\t\t\ttemp_var_{i}.AddRange(SerializeType(value_cast_{i}.{name}, false));");
                                }

                                if (member is IFieldSymbol field && !field.IsReadOnly)
                                    commit(field.Name, field.Type);
                            }
                        }

                        deserializeKnown.AppendLine($"\t\t\treturn Unsafe.As<{symname}, T>(ref temp_var_{i});");
                    }



                    deserializeKnown.AppendLine("\t\t}");


                    serialize.AppendLine($"\t\t\treturn writeTypeID ? [..BitConverter.GetBytes((ushort){i}), ..temp_var_{i}] : temp_var_{i}.ToArray();");

                    serialize.AppendLine("\t\t}");
                }





                deserializeKnown.AppendLine();
                deserializeKnown.AppendLine("\t\tthrow new NotImplementedException();");
                deserializeKnown.AppendLine("\t}");


                deserializeUnknown.AppendLine("\t\t\tdefault:");
                deserializeUnknown.AppendLine("\t\t\t\tthrow new NotImplementedException(\n#if DEBUG\n$\"Missing type ID {id}\"\n#endif\n);");
                deserializeUnknown.AppendLine("\t\t}");
                deserializeUnknown.AppendLine("\t}");


                serialize.AppendLine("\t\tthrow new NotImplementedException(\n#if DEBUG\n$\"Serialization for type '{value.GetType().FullName}' not generated, mark via attribute\"\n#endif\n);");
                serialize.AppendLine("\t}");



                sb.Append(deserializeKnown);
                sb.AppendLine();
                sb.AppendLine("//------------------------------------------------------------------------------------------");
                sb.AppendLine();
                sb.Append(deserializeUnknown);
                sb.AppendLine();
                sb.AppendLine("//------------------------------------------------------------------------------------------");
                sb.AppendLine();
                sb.Append(serialize);
                sb.AppendLine("}");



                spc.AddSource("Deserialize.g.cs", sb.ToString());
            });
    }




}