using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using System.Collections.Immutable;
using Engine.Attributes;



[Generator]
public sealed class StaticVirtualGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Step 1: Find all methods with [StaticVirtual] or [StaticVirtualOverride]
        var methods = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
                static (ctx, _) =>
                {
                    var method = (MethodDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(method) as IMethodSymbol;
                    if (symbol is null) return null;

                    bool hasAttr = symbol.GetAttributes().Any(a =>
                        a.AttributeClass?.Name is nameof(StaticVirtualAttribute) or nameof(StaticVirtualOverrideAttribute));

                    return hasAttr ? symbol.PartialDefinitionPart == null ? symbol : null : null;
                });

        var collected = methods.Where(static s => s is not null).Collect();

        // Step 2: Report diagnostics
        context.RegisterSourceOutput(collected, static (spc, allMethods) =>
        {
            foreach (var method in allMethods)
            {
                if (method is null) continue;
                var m = method;

                var attr = m.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.Name is nameof(StaticVirtualAttribute) or nameof(StaticVirtualOverrideAttribute));
                if (attr is null) continue;

                var attrName = attr.AttributeClass!.Name;
                var location = m.Locations.FirstOrDefault();

                if (attrName == nameof(StaticVirtualAttribute))
                {
                    var diag = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            id: "SV0001",
                            title: "Static virtual registered",
                            messageFormat: $"[StaticVirtual] method '{m.Name}' is registered for static dispatch.",
                            category: "StaticVirtual",
                            defaultSeverity: DiagnosticSeverity.Info,
                            isEnabledByDefault: true),
                        location);
                    spc.ReportDiagnostic(diag);
                }
                else if (attrName == nameof(StaticVirtualOverrideAttribute))
                {
                    // Validate override matches a base [StaticVirtual]
                    var baseMethod = FindBaseMethod(m);
                    bool hasBase = baseMethod != m;

                    var diag = Diagnostic.Create(
                        new DiagnosticDescriptor(
                            id: hasBase ? "SV0002" : "SV0003",
                            title: hasBase ? "Valid static virtual override" : "Invalid static virtual override",
                            messageFormat: hasBase
                                ? $"[StaticVirtualOverride] '{m.Name}' correctly overrides a base static virtual."
                                : $"[StaticVirtualOverride] '{m.Name}' does not match any [StaticVirtual] in base types.",
                            category: "StaticVirtual",
                            defaultSeverity: hasBase ? DiagnosticSeverity.Info : DiagnosticSeverity.Error,
                            isEnabledByDefault: true),
                        location);
                    spc.ReportDiagnostic(diag);
                }
            }
        });

        // Step 3: Generate static virtual dispatch methods
        context.RegisterSourceOutput(collected, static (spc, allMethods) =>
        {

            var methodsList = allMethods.Where(m => m is not null).Select(m => m!).ToArray();
            if (methodsList.Length == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("public static class StaticVirtuals");
            sb.AppendLine("{");

            static string Clean(ITypeSymbol type) =>
                type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .Replace("global::", "");

            // Filter only valid methods for generation
            var validMethods = methodsList.Where(m =>
            {
                var attr = m.GetAttributes().FirstOrDefault(a =>
                    a.AttributeClass?.Name is nameof(StaticVirtualAttribute) or nameof(StaticVirtualOverrideAttribute));
                if (attr is null) return false;

                if (attr.AttributeClass!.Name == nameof(StaticVirtualAttribute))
                    return true;

                // Only include override if a matching base [StaticVirtual] exists with full signature
                return FindBaseMethod(m) != m;
            }).ToArray();

            // Group methods by base method (family)
            var families = validMethods.GroupBy(m =>
            {
                var baseMethod = FindBaseMethod(m);
                var baseType = Clean(baseMethod.ContainingType);
                var paramTypes = string.Join(",", m.Parameters.Select(p => Clean(p.Type)));
                var returnType = Clean(m.ReturnType);
                return $"{baseType}:{m.Name}({paramTypes}):{returnType}";
            });

            foreach (var family in families)
            {
                var sample = family.First();
                var baseMethod = FindBaseMethod(sample);
                var baseTypeName = Clean(baseMethod.ContainingType);
                var methodName = sample.Name;
                var returnType = Clean(sample.ReturnType);

                var paramTypes = sample.Parameters.Select(p => Clean(p.Type)).ToArray();
                var paramNames = sample.Parameters.Select(p => p.Name).ToArray();
                var paramList = string.Join(", ", paramTypes.Zip(paramNames, (t, n) => $"{t} {n}"));

                sb.AppendLine();
                sb.AppendLine($"    public static {returnType} {baseTypeName.Replace('.', '_')}_{methodName}<T>({paramList}) where T : {baseTypeName}");
                sb.AppendLine("    {");

                // Emit dispatch for valid types only
                var ordered = family.OrderByDescending(m =>
                {
                    int depth = 0;
                    var t = m.ContainingType;
                    while (t.BaseType != null && t.BaseType.SpecialType != SpecialType.System_Object)
                    {
                        depth++;
                        t = t.BaseType;
                    }
                    return depth;
                });

                foreach (var m in ordered)
                {
                    var typeName = Clean(m.ContainingType);
                    var args = string.Join(", ", paramNames);

                    if (m.ReturnsVoid)
                    {
                        sb.AppendLine($"        if (typeof(T) == typeof({typeName}))");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            {typeName}.{methodName}({args});");
                        sb.AppendLine("            return;");
                        sb.AppendLine("        }");
                    }
                    else
                    {
                        sb.AppendLine(
                            $"        if (typeof(T) == typeof({typeName})) return {typeName}.{methodName}({args});"
                        );
                    }
                }

                sb.AppendLine($"        throw new MissingMethodException();");
                sb.AppendLine("    }");
            }

            sb.AppendLine("}");
            spc.AddSource("StaticVirtuals.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));

           
        });

        // Helper: find original [StaticVirtual] method for a family, matching full signature
        static IMethodSymbol FindBaseMethod(IMethodSymbol m)
        {
            var type = m.ContainingType.BaseType;

            while (type != null && type.SpecialType != SpecialType.System_Object)
            {
                foreach (var baseMember in type.GetMembers(m.Name).OfType<IMethodSymbol>())
                {
                    // Must have [StaticVirtual]
                    if (!baseMember.GetAttributes().Any(a => a.AttributeClass?.Name == nameof(StaticVirtualAttribute)))
                        continue;

                    // Match full signature: parameters + return type
                    bool signatureMatches =
                        baseMember.Parameters.Length == m.Parameters.Length &&
                        baseMember.Parameters.Zip(m.Parameters, (a, b) => SymbolEqualityComparer.Default.Equals(a.Type, b.Type)).All(x => x) &&
                        SymbolEqualityComparer.Default.Equals(baseMember.ReturnType, m.ReturnType);

                    if (signatureMatches)
                        return baseMember;
                }

                type = type.BaseType;
            }

            return m; // No valid base found
        }
    }
}
